### ISSUE TITLE
Toggle button does not work in Vaadin 23

### ISSUE THREAD

**Issue by jcgueriaud1** [vaadin-component-factory/toggle-button#10]
The structure of the checkbox in Vaadin 23 has changed and the style is not applied correctly anymore.
![image](https://user-images.githubusercontent.com/51313578/156983544-dc6b264e-9b73-4d86-bee7-e2d6ed2f1c2e.png)

I'm wondering if we need a new webcomponent for this, we could apply directly the style on the vaadin-checkbox itself and use the label of the checkbox.
It will be more accessible (since we are using element in light dom instead of shadow dom and the label for the right input).

Here is a prototype for the style: https://github.com/vaadin/web-components/issues/893

**Comment by fishermans** [comment]
+1

**Comment by kyberorg** [comment]
There is workaround.
Add those styles
```css
:host(.toggle-button) [part='checkbox']::after {
    width: calc(1.15em - 4px);
    height: calc(1.15em - 4px);
}
```

and in your main layout (or class where toggle button is used) add import
```java
@CssImport(value = "styles/components/vaadin-checkbox.css", themeFor = "vaadin-checkbox")
```

Taken from comments on component https://vaadin.com/directory/component/togglebutton-for-flow/discussions

**Comment by fishermans** [comment]
Yes, I know. Thanks.

Should be:

```css
:host(.toggle-button) [part='checkbox']::after {
    width: calc(1.2em - 4px);
    height: calc(1.1em - 4px);
}
```

But this component should have been fixed and recompiled against latest codebase from my-point-of-view.
