### ISSUE TITLE
checkbox-size fix ? 

### ISSUE THREAD

**Issue by rucko24** [vaadin-component-factory/toggle-button#18]
![image](https://github.com/user-attachments/assets/1ceef1cc-1a65-481f-b68f-ac06a4ab1fbb)

This is rendered in the shadow dom

![image](https://github.com/user-attachments/assets/c8a23042-2df5-4393-b70f-205d0d7ef4d1)

```css
--checkbox-size: 18px <1>
```
<1> Solved the problem maybe xD

Tested with 3.0.0 on Chrome and Mozilla with flow 24.5.1, and linux

**Comment by Alexenon** [comment]
Same issue here

![Image](https://github.com/user-attachments/assets/0c1e91d9-1cf2-41dc-b4a3-f08e0345e9d4)


Can I style the size of the switcher ?
Tried a couple of ways, but since it's using a Vaadin-checkbox inside the `#shadow-root`, I can't do very much...


That's the CSS properties I want to update: 

![Image](https://github.com/user-attachments/assets/9fc2ea52-be40-43b9-a924-620f0cbf0795)

```
vcf-toggle-button::part(checkbox)::after {
    top: 20px; // doesn't work
}
``` 


PS: Using Vaadin 24.2

**Comment by Alexenon** [comment]
After some time I found a way, using JS since #shadow-root is open, we can override the component style

```
private void normalize() {
    this.getElement().executeJs("""
            setTimeout(() => {
                const toggleButton = document.querySelector('vcf-toggle-button');
                const outerCheckbox = toggleButton?.shadowRoot?.querySelector('vaadin-checkbox');
                const checkboxShadow = outerCheckbox?.shadowRoot;
            
                const style = document.createElement('style');
                style.textContent = `
                    [part="checkbox"]::after {
                        content: '';
                        display: block;
                        position: absolute !important;
                        width: calc(1.4em - 4px) !important;
                        height: calc(1.4em - 4px) !important;
                        top: 0 !important;
                        left: 0 !important;
                    }
                `;
                checkboxShadow.appendChild(style);
            }, 100);
            """);
}
```

Was:
![Image](https://github.com/user-attachments/assets/01ca2800-e7a0-4fe4-803b-21f80a06c214)
Now:
![Image](https://github.com/user-attachments/assets/1166878a-c1c7-4688-8ff1-2398925ec2b0)

**Comment by rucko24** [comment]
Your approach is interesting. I had a file called vaadin-checkbox.css in the components folder with:

- Where do you execute the `normalize()` method? 

...

- Main css

```csss
--toggle-size: 18px;
```

vaadin-checkbox.css

```css
:host {
  color: var(--vaadin-checkbox-label-color, var(--lumo-body-text-color));
      font-size: var(--vaadin-checkbox-label-font-size, var(--lumo-font-size-m));
      font-family: var(--lumo-font-family);
      line-height: var(--lumo-line-height-s);
      -webkit-font-smoothing: antialiased;
      -moz-osx-font-smoothing: grayscale;
      -webkit-tap-highlight-color: transparent;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
      cursor: default;
      outline: none;
      --_checkbox-size: var(--toggle-size); Here ################################################
      --_color del anillo de enfoque: var(--vaadin-color del anillo de enfoque, var(--lumo-color primario-50pct));
      --_ancho del anillo de enfoque: var(--vaadin-ancho del anillo de enfoque, 2px);
      --_color de selección: var(--vaadin-color de selección, var(--lumo-color primario));
      --_invalid-background: var(--vaadin-input-field-invalid-background, var(--lumo-error-color-10pct));
      --_disabled-checkmark-color: var(--vaadin-checkbox-disabled-checkmark-color, var(--lumo-contrast-30pct));
}
```
